DATASET:
  NAME: "OxfordFlowers"
  # ATTRIBUTE_FILE: "/raid/biplab/datasets/sourav/data/oxford_flowers/attributes/sampled_attributes.json"
  ATTRIBUTE_FILE: "/raid/biplab/souravr/thesis/multimodal/AGL/data/oxford_flowers/attributes/oxford_flowers_attributes.json"
  NUM_ATTRIBUTES: 10